apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 3

  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: omercaner/python-app
        imagePullPolicy: ""
        name: web
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: test
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: web
type: NodePort
status:
  loadBalancer: {}
